<Project>
    <PropertyGroup>
        <ParentDirectoryBuildPropsPath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</ParentDirectoryBuildPropsPath>
    </PropertyGroup>
    <ImportGroup>
        <Import Project="$(ParentDirectoryBuildPropsPath)" />
    </ImportGroup>

    <PropertyGroup>
        <!-- Do not enforce documentations for test projects -->
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <IsTestProject Condition="$(MSBuildProjectName.IndexOf('Tests')) != -1">True</IsTestProject>
    </PropertyGroup>

    <Target Name="EchoIsTestProject" BeforeTargets="VSTest">
        <Message Text="IsTestProject is '$(IsTestProject)' for '$(MSBuildProjectName)'." Importance="high" />
    </Target>

    <ItemGroup Label="Implicit Test Packages" Condition="'$(IsTestProject)' == 'True'">
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

</Project>
